# Generated by Django 2.0.3 on 2019-04-08 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 15, 40, 5, 652828)),
        ),
    ]
